---
services:
  postgres:
    extends:
      service: "postgres"
      file: "./docker/postgres.yaml"
    volumes:
    - "db-data:/var/lib/postgresql/data"
  flyway:
    extends:
      service: "flyway"
      file: "./docker/flyway.yaml"
    depends_on:
      postgres:
        condition: "service_healthy"
volumes:
  db-data: null
