---
services:
  postgres:
    build:
      context: "./postgres"
    hostname: "${DATASOURCE_TODO_HOST}"
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: "Asia/Tokyo"
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_ROOT_PASSWORD: "${DATASOURCE_ROOT_PASSWORD}"
      POSTGRES_ADMIN_USERNAME: "${DATASOURCE_TODO_ADMIN_USERNAME}"
      POSTGRES_ADMIN_PASSWORD: "${DATASOURCE_TODO_ADMIN_PASSWORD}"
      POSTGRES_OPERATIONS_USERNAME: "${DATASOURCE_TODO_OPERATIONS_USERNAME}"
      POSTGRES_OPERATIONS_PASSWORD: "${DATASOURCE_TODO_OPERATIONS_PASSWORD}"
      POSTGRES_PRODUCTION_DBNAME: "${DATASOURCE_TODO_DBNAME}"
      POSTGRES_TEST_DBNAME: "${DATASOURCE_TODO_TEST_DBNAME}"
    ports:
    - "${DATASOURCE_TODO_PORT}:5432"
    healthcheck:
      test:
      - "CMD-SHELL"
      - "pg_isready"
      interval: "10s"
      timeout: "5s"
      retries: "3"
    restart: "unless-stopped"
