---
services:
  postgres:
    build:
      context: "./postgres"
    hostname: "${DB_HOST}"
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: "Asia/Tokyo"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
    - "${DB_PORT}:5432"
    healthcheck:
      test:
      - "CMD-SHELL"
      - "pg_isready"
      interval: "10s"
      timeout: "5s"
      retries: "3"
    restart: "unless-stopped"
