CREATE TABLE IF NOT EXISTS tags (id SERIAL PRIMARY KEY, "name" VARCHAR(255) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL);
ALTER TABLE tags ADD CONSTRAINT tags_name_unique UNIQUE ("name");
CREATE INDEX tags_created_at ON tags (created_at);
CREATE SEQUENCE IF NOT EXISTS tags_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
ALTER TABLE task_associated_tags ADD CONSTRAINT fk_task_associated_tags_tag_id__id FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE RESTRICT ON UPDATE RESTRICT;
