CREATE TABLE IF NOT EXISTS task_status (id SERIAL PRIMARY KEY, task_id uuid NOT NULL, status VARCHAR(5) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, CONSTRAINT fk_task_status_task_id__id FOREIGN KEY (task_id) REFERENCES task_id(id) ON DELETE RESTRICT ON UPDATE RESTRICT);
CREATE INDEX task_status_created_at ON task_status (created_at);
CREATE SEQUENCE IF NOT EXISTS task_status_id_seq START WITH 1 MINVALUE 1 MAXVALUE 9223372036854775807;
ALTER TABLE task_id DROP COLUMN account_id;
