---
name: "Check lint and test"
"on":
  pull_request: null
jobs:
  check:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10

    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v5"

      - name: "Restore gradle caches"
        uses: "./.github/actions/gradle-cache"

      - name: "Check with Gradle"
        uses: "./.github/actions/gradle-action"
        with:
          command: "check -x integrationTest"
