---
name: "on-pull-request"
"on":
  pull_request: null
jobs:
  check:
    runs-on: "ubuntu-latest"
    timeout-minutes: 10
    steps:
    - name: "Checkout Repository"
      uses: "actions/checkout@v5"
    - name: "Gradle Cache"
      uses: "./.github/actions/gradle-cache"
    - name: "Check with Gradle"
      uses: "./.github/actions/gradle-action"
      with:
        command: "check"
